name: Build
on: push
jobs:
  compile-rom:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/gbdev/rgbds:v0.9.2
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Make output directories
        run: |
          mkdir -p assets
          chmod 777 assets
          mkdir -p bin
          chmod 777 bin
      - name: Install RGBDS
        run: |
          install -s -m 755 /rgbds/rgbasm /rgbds/rgblink /rgbds/rgbfix /rgbds/rgbgfx /usr/local/bin/
      - name: Compile ROM
        run: make
      - name: Upload ROM
        uses: actions/upload-artifact@v4
        with:
          name: ez-maze
          path: bin/maze.gb
