name: Build
on: push
jobs:
  compile-rom:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/gbdev/rgbds:v0.9.2
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Make output directories
        run: |
          mkdir -p assets
          chmod 777 assets
          mkdir -p bin
          chmod 777 bin
      - name: Install RGBDS
        run: /rgbds/.github/scripts/install.sh
      - name: List files
        run: |
          ls -al
          rgbgfx
      - name: Compile ROM
        run: make
      - name: Upload ROM
        uses: actions/upload-artifact@v4
        with:
          name: ROM
          path: bin/maze.gb
